import { Inter } from 'next/font/google';

import { GlobalProvider } from '@/context/GlobalState';
import './styles/globals.css';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://uploads-ssl.webflow.com/64afbac816bb17eb2fdc3f03/css/everest-wealth.webflow.2f2aa5550.css"
          rel="stylesheet"
          type="text/css"
        />
      </head>
      <body className={inter.className}>
        <GlobalProvider>
          {children}
        </GlobalProvider>
      </body>
    </html>
  )
}
